require('plugins.cmp')
require('plugins.fidget')
require('plugins.lualine')
require('plugins.mini')
require('plugins.snacks')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.undotree')
